language: go
go:
  - "1.12"
  - tip
script:
  - go build
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic
  - go test -bench=. -cpu=4 -benchmem
after_script:
  - bash <(curl -s https://codecov.io/bash)
